
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nl.cape.academy.solidprinciples;
import org.junit.Test;
import static org.junit.Assert.*;
public class AppTest {
    
}